// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCS7sj0TkG-zpJY034ryk8hHHy4II-fo',
    appId: '1:1056439622994:web:83a3a5d1c3bd2ee09cae8b',
    messagingSenderId: '1056439622994',
    projectId: 'blooddonors-99958',
    authDomain: 'blooddonors-99958.firebaseapp.com',
    storageBucket: 'blooddonors-99958.appspot.com',
    measurementId: 'G-J2CS4X3PM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69V0WlcCUesWu3soUiE5LQc5gM_yRI4E',
    appId: '1:1056439622994:android:9c51ef076e28b76a9cae8b',
    messagingSenderId: '1056439622994',
    projectId: 'blooddonors-99958',
    storageBucket: 'blooddonors-99958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv9sb3c8drGgPBDgmMh7WybHqMZnMJe0E',
    appId: '1:1056439622994:ios:7c06654573dd39e79cae8b',
    messagingSenderId: '1056439622994',
    projectId: 'blooddonors-99958',
    storageBucket: 'blooddonors-99958.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv9sb3c8drGgPBDgmMh7WybHqMZnMJe0E',
    appId: '1:1056439622994:ios:7c06654573dd39e79cae8b',
    messagingSenderId: '1056439622994',
    projectId: 'blooddonors-99958',
    storageBucket: 'blooddonors-99958.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjCS7sj0TkG-zpJY034ryk8hHHy4II-fo',
    appId: '1:1056439622994:web:a36db7ae36071da19cae8b',
    messagingSenderId: '1056439622994',
    projectId: 'blooddonors-99958',
    authDomain: 'blooddonors-99958.firebaseapp.com',
    storageBucket: 'blooddonors-99958.appspot.com',
    measurementId: 'G-L6LBLWLRD0',
  );
}
